/**
 * Initial source registry. Disabled entries are documented targets whose
 * exact endpoint must be verified before production use.
 */
export const SOURCES = [
  {
    id: "gdelt-greek-telco",
    type: "gdelt",
    enabled: false,
    url: "https://api.gdeltproject.org/api/v2/doc/doc",
    query: '(OTE OR Cosmote OR Vodafone OR Nova OR "PPC Fiber" OR "United Fiber" OR EETT) (FTTH OR fiber OR fibre OR 5G OR broadband OR spectrum OR network)',
    timespan: "7days",
    limit: 125,
  },
  {
    id: "gdelt-greek-energy",
    type: "gdelt",
    enabled: false,
    url: "https://api.gdeltproject.org/api/v2/doc/doc",
    query: '(ADMIE OR IPTO OR HEDNO OR DESFA OR RAAEY OR PPC OR DEPA) (grid OR substation OR interconnection OR storage OR renewable OR electricity OR gas)',
    timespan: "7days",
    limit: 125,
  },
  {
    id: "gdelt-greek-finance",
    type: "gdelt",
    enabled: false,
    url: "https://api.gdeltproject.org/api/v2/doc/doc",
    query: '("Alpha Bank" OR Eurobank OR "National Bank of Greece" OR "Piraeus Bank" OR ATHEX OR "Athens Stock Exchange") (results OR earnings OR dividend OR acquisition OR bond OR loan OR capital)',
    timespan: "7days",
    limit: 125,
  },
  {
    id: "gdelt-greek-infrastructure",
    type: "gdelt",
    enabled: false,
    url: "https://api.gdeltproject.org/api/v2/doc/doc",
    query: '(Greece OR Greek) (infrastructure OR construction OR concession OR railway OR motorway OR "data center" OR subsea cable)',
    timespan: "7days",
    limit: 125,
  },
  {
    id: "ot-wordpress",
    type: "wordpress",
    enabled: false,
    url: "https://www.ot.gr",
    lookbackDays: 7,
    limit: 100,
  },
  {
    id: "eett-announcements",
    type: "html",
    url: "https://www.eett.gr/mme-ekdoseis/deltia-typou-anakoinoseis/",
    linkPatterns: ["anakoin", "deltio", "decision"],
    limit: 100,
  },
  {
    id: "raaey-energy-announcements",
    type: "html",
    url: "https://www.raaey.gr/energeia/anakinoseis/",
    linkPatterns: ["anakoin", "αδει", "storage", "energy"],
    limit: 100,
  },
  {
    id: "ypen-energy-announcements",
    type: "html",
    url: "https://ypen.gov.gr/category/anakoinoseis-typou/",
    linkPatterns: ["energia", "ενεργ", "anakoin", "press"],
    limit: 100,
  },
  {
    id: "ggtt-telecom-announcements",
    type: "html",
    url: "https://ggtt.mindigital.gr/section/telecom",
    linkPatterns: ["telecom", "post", "news", "announcement", "τηλεπικ"],
    limit: 100,
  },
  {
    id: "ot-telecoms",
    type: "html",
    url: "https://www.ot.gr/category/epixeiriseis/tilepikoinonies/",
    linkPatterns: ["tilepikoin", "ote", "cosmote", "vodafone", "nova", "ftth", "fiber", "fibre", "5g", "network", "telekom"],
    minimumTitleLength: 16,
    timeoutMs: 20000,
    limit: 100,
  },
  {
    id: "netweek-telecoms",
    type: "html",
    url: "https://netweek.gr/category/telecoms/",
    linkPatterns: ["telecom", "ote", "cosmote", "vodafone", "nova", "ftth", "fiber", "fibre", "5g", "ufbb", "network", "connectivity", "τηλεπικ"],
    minimumTitleLength: 16,
    limit: 120,
  },
  {
    id: "naftemporiki-telecoms",
    type: "html",
    url: "https://www.naftemporiki.gr/tag/tilepikoinonies/",
    linkPatterns: ["tilepikoin", "telecom", "ote", "cosmote", "vodafone", "nova", "ftth", "fiber", "fibre", "5g", "network", "internet", "δικτυ", "κινητ"],
    minimumTitleLength: 16,
    limit: 120,
  },
  {
    id: "dnews-eett",
    type: "html",
    url: "https://www.dnews.gr/site/tag/%CE%95%CE%95%CE%A4%CE%A4",
    linkPatterns: ["eett", "%CE%95%CE%95%CE%A4%CE%A4", "eidhseis", "tilepikoin", "telecom", "mobile", "χρεω"],
    minimumTitleLength: 16,
    limit: 100,
  },
  {
    id: "intracom-telecom-press",
    type: "html",
    url: "https://www.intracom-telecom.com/en/news/press.htm",
    linkPatterns: ["/en/news/press/"],
    minimumTitleLength: 16,
    limit: 100,
  },
  {
    id: "energypress-wordpress",
    type: "wordpress",
    enabled: false,
    url: "https://energypress.gr",
    lookbackDays: 7,
    limit: 100,
  },
  {
    id: "ypodomes-wordpress",
    type: "wordpress",
    url: "https://ypodomes.com",
    lookbackDays: 7,
    limit: 100,
  },
  {
    id: "insider-wordpress",
    type: "wordpress",
    enabled: false,
    url: "https://www.insider.gr",
    lookbackDays: 7,
    limit: 100,
  },
  {
    id: "naftemporiki",
    type: "rss",
    url: "https://www.naftemporiki.gr/feed/",
  },
  {
    id: "ot-gr",
    type: "rss",
    url: "https://www.ot.gr/feed/",
  },
  {
    id: "google-news-greek-telco",
    type: "rss",
    url: "https://news.google.com/rss/search?q=%28OTE%20OR%20Cosmote%20OR%20Vodafone%20OR%20Nova%20OR%20Intracom%20OR%20FTTH%20OR%205G%20OR%20telecom%20OR%20%CF%84%CE%B7%CE%BB%CE%B5%CF%80%CE%B9%CE%BA%CE%BF%CE%B9%CE%BD%CF%89%CE%BD%CE%AF%CE%B5%CF%82%20OR%20%CE%95%CE%95%CE%A4%CE%A4%29%20Greece&hl=el&gl=GR&ceid=GR%3Ael",
    limit: 60,
  },
  {
    id: "google-news-greek-energy",
    type: "rss",
    url: "https://news.google.com/rss/search?q=%28ADMIE%20OR%20IPTO%20OR%20HEDNO%20OR%20DEDDIE%20OR%20RAAEY%20OR%20PPC%20OR%20renewable%20OR%20storage%29%20Greece&hl=el&gl=GR&ceid=GR%3Ael",
    limit: 60,
  },
];
